const products = [
  {
    id: 1,
    title: "Asymmetrical Fitted T-shirt",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/women/a5.jpg",
    img1: "Pics/women/a5.jpg",
    img2: "Pics/women/a6.jpg",
    img3: "Pics/women/a7.jpg",
    img4: "Pics/women/a8.jpg",
    img5: "Pics/women/a9.jpg",
  },
  {
    id: 2,
    title: "Asymmetrical Fitted T-shirt",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/women/a1.jpg",
    img1: "Pics/women/a1.jpg",
    img2: "Pics/women/a2.jpg",
    img3: "Pics/women/a3.jpg",
    img4: "Pics/women/a4.jpg",
  },
  {
    id: 3,
    title: "Slim Fit Mini Dresses",
    price: "$ " + 17.59,
    size: ["S", "M", "L"],
    show: "Pics/women/b1.jpg",
    img1: "Pics/women/b1.jpg",
    img2: "Pics/women/b2.jpg",
    img3: "Pics/women/b3.jpg",
    img4: "Pics/women/b4.jpg",
    img5: "Pics/women/b5.jpg",
  },
  {
    id: 4,
    title: "Slim Fit Mini Dresses",
    price: "$ " + 17.59,
    size: ["S", "M", "L"],
    show: "Pics/women/b11.jpg",
    img1: "Pics/women/b11.jpg",
    img2: "Pics/women/b22.jpg",
    img3: "Pics/women/b33.jpg",
    img4: "Pics/women/b44.jpg",
    img5: "Pics/women/b55.jpg",
  },
  {
    id: 5,
    title: "Slim Fit T-Shirt",
    price: "$ " + 15.59,
    size: ["S", "M", "L"],
    show: "Pics/women/c1.jpg",
    img1: "Pics/women/c1.jpg",
    img2: "Pics/women/c2.jpg",
    img3: "Pics/women/c3.jpg",
    img4: "Pics/women/c4.jpg",
    img5: "Pics/women/c5.jpg",
  },
  {
    id: 6,
    title: "Slim Fit T-Shirt",
    price: "$ " + 15.59,
    size: ["S", "M", "L"],
    show: "Pics/women/c11.jpg",
    img1: "Pics/women/c11.jpg",
    img2: "Pics/women/c22.jpg",
    img3: "Pics/women/c33.jpg",
    img4: "Pics/women/c44.jpg",
    img5: "Pics/women/c55.jpg",
  },
  {
    id: 7,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/women/d1.jpg",
    img1: "Pics/women/d1.jpg",
    img2: "Pics/women/d2.jpg",
    img3: "Pics/women/d3.jpg",
    img4: "Pics/women/d4.jpg",
    img5: "Pics/women/d5.jpg",
  },
  {
    id: 8,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/aa/aa1.jpg",
    img1: "Pics/pic/aa/aa1.jpg",
    img2: "Pics/pic/aa/aa3.jpg",
    img3: "Pics/pic/aa/aa4.jpg",
    img4: "Pics/pic/aa/aa5.jpg",
    img5: "Pics/pic/aa/aa6.jpg",
  },
  {
    id: 9,
    title: "Regular Fit Jacket",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/bb/bb1.jpg",
    img1: "Pics/pic/bb/bb1.jpg",
    img2: "Pics/pic/bb/bb2.jpg",
    img3: "Pics/pic/bb/bb3.jpg",
    img4: "Pics/pic/bb/bb4.jpg",
    img5: "Pics/pic/bb/bb5.jpg",
  },
  {
    id: 10,
    title: "Sport Life UV-Windbreaker",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/cc/cc1.jpg",
    img1: "Pics/pic/cc/cc1.jpg",
    img2: "Pics/pic/cc/cc2.jpg",
    img3: "Pics/pic/cc/cc3.jpg",
    img4: "Pics/pic/cc/cc4.jpg",
    img5: "Pics/pic/cc/cc5.jpg",
  },
  {
    id: 11,
    title: "Loose Fit Denim Jackets",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/dd/dd1.jpg",
    img1: "Pics/pic/dd/dd1.jpg",
    img2: "Pics/pic/dd/dd2.jpg",
    img3: "Pics/pic/dd/dd3.jpg",
    img4: "Pics/pic/dd/dd4.jpg",
    img5: "Pics/pic/dd/dd5.jpg",
  },
  {
    id: 12,
    title: "Black Mini Mesh Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/ee/ee1.jpg",
    img1: "Pics/pic/ee/ee1.jpg",
    img2: "Pics/pic/ee/ee2.jpg",
    img3: "Pics/pic/ee/ee3.jpg",
    img4: "Pics/pic/ee/ee4.jpg",
  },
  {
    id: 13,
    title: "Regular Floral Mini Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/ff/ff1.jpg",
    img1: "Pics/pic/ff/ff1.jpg",
    img2: "Pics/pic/ff/ff2.jpg",
    img3: "Pics/pic/ff/ff3.jpg",
    img4: "Pics/pic/ff/ff4.jpg",
    img5: "Pics/pic/ff/ff5.jpg",
  },
  {
    id: 14,
    title: "Mexi Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/gg/gg1.jpg",
    img1: "Pics/pic/gg/gg1.jpg",
    img2: "Pics/pic/gg/gg2.jpg",
    img3: "Pics/pic/gg/gg3.jpg",
    img4: "Pics/pic/gg/gg4.jpg",
    img5: "Pics/pic/gg/gg5.jpg",
  },
  {
    id: 15,
    title: "Mini Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/hh/hh1.jpg",
    img1: "Pics/pic/hh/hh1.jpg",
    img2: "Pics/pic/hh/hh2.jpg",
    img3: "Pics/pic/hh/hh3.jpg",
    img4: "Pics/pic/hh/hh4.jpg",
    img5: "Pics/pic/hh/hh5.jpg",
  },
  {
    id: 16,
    title: "Party-Maxi Pleats Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/ii/ii1.jpg",
    img1: "Pics/pic/ii/ii1.jpg",
    img2: "Pics/pic/ii/ii2.jpg",
    img3: "Pics/pic/ii/ii3.jpg",
    img4: "Pics/pic/ii/ii4.jpg",
    img5: "Pics/pic/ii/ii5.jpg",
  },
  {
    id: 17,
    title: "Mini Lace Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/jj/jj1.jpg",
    img1: "Pics/pic/jj/jj1.jpg",
    img2: "Pics/pic/jj/jj2.jpg",
    img3: "Pics/pic/jj/jj3.jpg",
    img4: "Pics/pic/jj/jj4.jpg",
    img5: "Pics/pic/jj/jj5.jpg",
  },
  {
    id: 18,
    title: "Midi Corset Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/kk/kk1.jpg",
    img1: "Pics/pic/kk/kk1.jpg",
    img2: "Pics/pic/kk/kk2.jpg",
    img3: "Pics/pic/kk/kk3.jpg",
    img4: "Pics/pic/kk/kk4.jpg",
    img5: "Pics/pic/kk/kk5.jpg",
  },
  {
    id: 19,
    title: "Regular Printed T-Shirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/q/q1.jpg",
    img1: "Pics/pic/q/q1.jpg",
    img2: "Pics/pic/q/q2.jpg",
    img3: "Pics/pic/q/q3.jpg",
    img4: "Pics/pic/q/q4.jpg",
    img5: "Pics/pic/q/q5.jpg",
  },
  {
    id: 20,
    title: "Trai Sport Life Windbreaker",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/t/t2.jpg",
    img1: "Pics/pic/t/t2.jpg",
    img2: "Pics/pic/t/t7.jpg",
    img3: "Pics/pic/t/t3.jpg",
    img4: "Pics/pic/t/t4.jpg",
    img5: "Pics/pic/t/t5.jpg",
  },
  {
    id: 20,
    title: "Trai Sport Life Windbreaker",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/t/t2.jpg",
    img1: "Pics/pic/t/t2.jpg",
    img2: "Pics/pic/t/t7.jpg",
    img3: "Pics/pic/t/t3.jpg",
    img4: "Pics/pic/t/t4.jpg",
    img5: "Pics/pic/t/t5.jpg",
  },
  {
    id: 21,
    title: "Sport Life Short Sleeves T-Shirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/u/u1.jpg",
    img1: "Pics/pic/u/u1.jpg",
    img2: "Pics/pic/u/u2.jpg",
    img3: "Pics/pic/u/u3.jpg",
    img4: "Pics/pic/u/u4.jpg",
  },
  {
    id: 22,
    title: "Long Slim Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/v/v1.jpg",
    img1: "Pics/pic/v/v1.jpg",
    img2: "Pics/pic/v/v2.jpg",
    img3: "Pics/pic/v/v3.jpg",
    img4: "Pics/pic/v/v4.jpg",
    img5: "Pics/pic/v/v5.jpg",
  },
  {
    id: 23,
    title: "Unisex-Café Boxy T-Shirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/w/w1.jpg",
    img1: "Pics/pic/w/w1.jpg",
    img2: "Pics/pic/w/w2.jpg",
    img3: "Pics/pic/w/w3.jpg",
    img4: "Pics/pic/w/w4.jpg",
    img5: "Pics/pic/w/w5.jpg",
  },
  {
    id: 24,
    title: "Relaxed T-Shirt With Printed",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/x/x1.jpg",
    img1: "Pics/pic/x/x1.jpg",
    img2: "Pics/pic/x/x2.jpg",
    img3: "Pics/pic/x/x3.jpg",
    img4: "Pics/pic/x/x4.jpg",
    img5: "Pics/pic/x/x5.jpg",
  },
  {
    id: 25,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/y/y1.jpg",
    img1: "Pics/pic/y/y1.jpg",
    img2: "Pics/pic/y/y2.jpg",
    img3: "Pics/pic/y/y3.jpg",
    img4: "Pics/pic/y/y4.jpg",
    img5: "Pics/pic/y/y5.jpg",
  },
  {
    id: 26,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/z/z1.jpg",
    img1: "Pics/pic/z/z1.jpg",
    img2: "Pics/pic/z/z2.jpg",
    img3: "Pics/pic/z/z3.jpg",
    img4: "Pics/pic/z/z4.jpg",
    img5: "Pics/pic/z/zz5.jpg",
  },
  {
    id: 27,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/aaa/aaa1.jpg",
    img1: "Pics/pic/pic/aaa/aaa1.jpg",
    img2: "Pics/pic/pic/aaa/aaa3.jpg",
    img3: "Pics/pic/pic/aaa/aaa4.jpg",
    img4: "Pics/pic/pic/aaa/aaa5.jpg",
    img5: "Pics/pic/pic/aaa/aaa2.jpg",
  },
  {
    id: 28,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/bbb/bbb1.jpg",
    img1: "Pics/pic/pic/bbb/bbb1.jpg",
    img2: "Pics/pic/pic/bbb/bbb2.jpg",
    img3: "Pics/pic/pic/bbb/bbb3.jpg",
    img4: "Pics/pic/pic/bbb/bbb4.jpg",
    img5: "Pics/pic/pic/bbb/bbb5.jpg",
  },
  {
    id: 29,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/ccc1.jpg",
    img1: "Pics/pic/pic/ccc1.jpg",
    img2: "Pics/pic/pic/ccc2.jpg",
    img3: "Pics/pic/pic/ccc3.jpg",
    img4: "Pics/pic/pic/ccc4.jpg",
    img5: "Pics/pic/pic/ccc5.jpg",
  },
  {
    id: 30,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/ddd1.jpg",
    img1: "Pics/pic/pic/ddd1.jpg",
    img2: "Pics/pic/pic/ddd2.jpg",
    img3: "Pics/pic/pic/ddd3.jpg",
    img4: "Pics/pic/pic/ddd4.jpg",
    img5: "Pics/pic/pic/ddd5.jpg",
  },
  {
    id: 31,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/eee1.jpg",
    img1: "Pics/pic/pic/eee1.jpg",
    img2: "Pics/pic/pic/eee2.jpg",
    img3: "Pics/pic/pic/eee3.jpg",
    img4: "Pics/pic/pic/eee4.jpg",
    img5: "Pics/pic/pic/eee5.jpg",
  },
  {
    id: 32,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/ffff1.jpg",
    img1: "Pics/pic/pic/ffff1.jpg",
    img2: "Pics/pic/pic/ffff2.jpg",
    img3: "Pics/pic/pic/ffff3.jpg",
    img4: "Pics/pic/pic/ffff4.jpg",
    img5: "Pics/pic/pic/ffff5.jpg",
  },
  {
    id: 33,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/ggg1.jpg",
    img1: "Pics/pic/pic/ggg1.jpg",
    img2: "Pics/pic/pic/ggg2.jpg",
    img3: "Pics/pic/pic/ggg3.jpg",
    img4: "Pics/pic/pic/ggg4.jpg",
    img5: "Pics/pic/pic/ggg5.jpg",
  },
  {
    id: 34,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/hhh1.jpg",
    img1: "Pics/pic/pic/hhh1.jpg",
    img2: "Pics/pic/pic/hhh2.jpg",
    img3: "Pics/pic/pic/hhh3.jpg",
    img4: "Pics/pic/pic/hhh4.jpg",
    img5: "Pics/pic/pic/hhh5.jpg",
  },
  {
    id: 35,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/iii1.jpg",
    img1: "Pics/pic/pic/iii1.jpg",
    img2: "Pics/pic/pic/iii2.jpg",
    img3: "Pics/pic/pic/iii3.jpg",
    img4: "Pics/pic/pic/iii4.jpg",
    img5: "Pics/pic/pic/iii5.jpg",
  },
  {
    id: 36,
    title: "Halter Midi Dresses",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/jjj/jjj1.jpg",
    img1: "Pics/pic/pic/jjj/jjj1.jpg",
    img2: "Pics/pic/pic/jjj/jjj2.jpg",
    img3: "Pics/pic/pic/jjj/jjj6.jpg",
    img4: "Pics/pic/pic/jjj/jjj4.jpg",
    img5: "Pics/pic/pic/jjj/jjj5.jpg",
  },
  {
    id: 37,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/kkk1.jpg",
    img1: "Pics/pic/pic/kkk1.jpg",
    img2: "Pics/pic/pic/kkk2.jpg",
    img3: "Pics/pic/pic/kkk3.jpg",
    img4: "Pics/pic/pic/kkk4.jpg",
    img5: "Pics/pic/pic/kkk5.jpg",
  },
  {
    id: 38,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/lll1.jpg",
    img1: "Pics/pic/pic/lll1.jpg",
    img2: "Pics/pic/pic/lll2.jpg",
    img3: "Pics/pic/pic/lll3.jpg",
    img4: "Pics/pic/pic/lll4.jpg",
    img5: "Pics/pic/pic/lll5.jpg",
  },
  {
    id: 39,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/mmm1.jpg",
    img1: "Pics/pic/pic/mmm1.jpg",
    img2: "Pics/pic/pic/mmm2.jpg",
    img3: "Pics/pic/pic/mmm3.jpg",
    img4: "Pics/pic/pic/mmm4.jpg",
    img5: "Pics/pic/pic/mmm5.jpg",
  },
  {
    id: 40,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/nnn1.jpg",
    img1: "Pics/pic/pic/nnn1.jpg",
    img2: "Pics/pic/pic/nnn2.jpg",
    img3: "Pics/pic/pic/nnn3.jpg",
    img4: "Pics/pic/pic/nnn4.jpg",
    img5: "Pics/pic/pic/nnn5.jpg",
  },
  {
    id: 41,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/ooo1.jpg",
    img1: "Pics/pic/pic/ooo1.jpg",
    img2: "Pics/pic/pic/ooo2.jpg",
    img3: "Pics/pic/pic/ooo3.jpg",
    img4: "Pics/pic/pic/ooo4.jpg",
    img5: "Pics/pic/pic/ooo5.jpg",
  },
  {
    id: 42,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/ppp1.jpg",
    img1: "Pics/pic/pic/ppp1.jpg",
    img2: "Pics/pic/pic/ppp2.jpg",
    img3: "Pics/pic/pic/ppp3.jpg",
    img4: "Pics/pic/pic/ppp4.jpg",
    img5: "Pics/pic/pic/ppp5.jpg",
  },
  {
    id: 43,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/qqq1.jpg",
    img1: "Pics/pic/pic/qqq1.jpg",
    img2: "Pics/pic/pic/qqq2.jpg",
    img3: "Pics/pic/pic/qqq3.jpg",
    img4: "Pics/pic/pic/qqq4.jpg",
    img5: "Pics/pic/pic/qqq5.jpg",
  },
  {
    id: 44,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/rrr1.jpg",
    img1: "Pics/pic/pic/rrr1.jpg",
    img2: "Pics/pic/pic/rrr2.jpg",
    img3: "Pics/pic/pic/rrr3.jpg",
    img4: "Pics/pic/pic/rrr4.jpg",
    img5: "Pics/pic/pic/rrr5.jpg",
  },
  {
    id: 45,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/vvv1.jpg",
    img1: "Pics/pic/pic/vvv1.jpg",
    img2: "Pics/pic/pic/vvv2.jpg",
    img3: "Pics/pic/pic/vvv3.jpg",
    img4: "Pics/pic/pic/vvv4.jpg",
    img5: "Pics/pic/pic/vvv5.jpg",
  },
  {
    id: 46,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/www1.jpg",
    img1: "Pics/pic/pic/www1.jpg",
    img2: "Pics/pic/pic/www2.jpg",
    img3: "Pics/pic/pic/www3.jpg",
    img4: "Pics/pic/pic/www4.jpg",
    img5: "Pics/pic/pic/www5.jpg",
  },
  {
    id: 47,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/xxx1.jpg",
    img1: "Pics/pic/pic/xxx1.jpg",
    img2: "Pics/pic/pic/xxx2.jpg",
    img3: "Pics/pic/pic/xxx3.jpg",
    img4: "Pics/pic/pic/xxx4.jpg",
    img5: "Pics/pic/pic/xxx5.jpg",
  },
  {
    id: 48,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/yyy1.jpg",
    img1: "Pics/pic/pic/yyy1.jpg",
    img2: "Pics/pic/pic/yyy2.jpg",
    img3: "Pics/pic/pic/yyy3.jpg",
    img4: "Pics/pic/pic/yyy4.jpg",
    img5: "Pics/pic/pic/yyy5.jpg",
  },
  {
    id: 49,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/pic/zzz1.jpg",
    img1: "Pics/pic/pic/zzz1.jpg",
    img2: "Pics/pic/pic/zzz2.jpg",
    img3: "Pics/pic/pic/zzz3.jpg",
    img4: "Pics/pic/pic/zzz4.jpg",
    img5: "Pics/pic/pic/zzz5.jpg",
  },
  {
    id: 50,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/top/a1.jpg",
    img1: "Pics/pic/top/a1.jpg",
    img2: "Pics/pic/top/a2.jpg",
    img3: "Pics/pic/top/a3.jpg",
    img4: "Pics/pic/top/a4.jpg",
    img5: "Pics/pic/top/a5.jpg",
  },
  {
    id: 51,
    title: "Mini Skirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/top/b1.jpg",
    img1: "Pics/pic/top/b1.jpg",
    img2: "Pics/pic/top/b2.jpg",
    img3: "Pics/pic/top/b3.jpg",
    img4: "Pics/pic/top/b4.jpg",
    img5: "Pics/pic/top/b5.jpg",
  },
  {
    id: 52,
    title: "Double Gromment Belt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/top/belt (1).jpg",
    img1: "Pics/pic/top/belt (1).jpg",
    img2: "Pics/pic/top/belt (2).jpg",
    img3: "Pics/pic/top/belt (3).jpg",
  },
  {
    id: 53,
    title: "Shoulder Bag",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/top/bag1.jpg",
    img1: "Pics/pic/top/bag1.jpg",
    img2: "Pics/pic/top/bag2.jpg",
    img3: "Pics/pic/top/bag3.jpg",
    img4: "Pics/pic/top/bag4.jpg",
    img5: "Pics/pic/top/bag5.jpg",
  },
  {
    id: 54,
    title: "Cap With Embroidery",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/pic/top/c1.jpg",
    img1: "Pics/pic/top/c1.jpg",
    img2: "Pics/pic/top/c2.jpg",
    img3: "Pics/pic/top/c3.jpg",
    img4: "Pics/pic/top/c4.jpg",
    img5: "Pics/pic/top/c1.jpg",
  },
  {
    id: 55,
    title: "Wide Leg Cargo Jeans",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/man/j1.jpg",
    img1: "Pics/man/j1.jpg",
    img2: "Pics/man/j2.jpg",
    img3: "Pics/man/j3.jpg",
    img4: "Pics/man/j4.jpg",
    img5: "Pics/man/j2.jpg",
  },
  {
    id: 56,
    title: "Regular Printed T-Shirt",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/man/t1.jpg",
    img1: "Pics/man/t1.jpg",
    img2: "Pics/man/t2.jpg",
    img3: "Pics/man/t3.jpg",
    img4: "Pics/man/t4.jpg",
    img5: "Pics/man/t1.jpg",
  },
  {
    id: 57,
    title: "Sport Life Windbreaker",
    price: "$ " + 19.95,
    size: ["S", "M", "L"],
    show: "Pics/man/s1.jpg",
    img1: "Pics/man/s1.jpg",
    img2: "Pics/man/s2.jpg",
    img3: "Pics/man/s3.jpg",
    img4: "Pics/man/s4.jpg",
    img5: "Pics/man/s1.jpg",
  },
  {
    id: 58,
    title: "Belt",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/man/b1.jpg",
    img1: "Pics/man/b1.jpg",
    img2: "Pics/man/b2.jpg",
    img3: "Pics/man/b3.jpg",
    img4: "Pics/man/b2.jpg",
    img5: "Pics/man/b3.jpg",
  },
  {
    id: 59,
    title: "Dropper Hat",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/man/h1.jpg",
    img1: "Pics/man/h1.jpg",
    img2: "Pics/man/h2.jpg",
    img3: "Pics/man/h3.jpg",
    img4: "Pics/man/h2.jpg",
    img5: "Pics/man/h3.jpg",
  },
  {
    id: 60,
    title: "Cross Body Bag",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/man/16.jpg",
    img1: "Pics/man/16.jpg",
    img2: "Pics/man/17.jpg",
    img3: "Pics/man/18.jpg",
    img4: "Pics/man/19.jpg",
    img5: "Pics/man/16.jpg",
  },
  {
    id: 61,
    title: "Cross Body Bag",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/man/11.jpg",
    img1: "Pics/man/11.jpg",
    img2: "Pics/man/12.jpg",
    img3: "Pics/man/13.jpg",
    img4: "Pics/man/14.jpg",
    img5: "Pics/man/15.jpg",
  },
  {
    id: 62,
    title: "Mini Shoulder Bag",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/man/1.jpg",
    img1: "Pics/man/1.jpg",
    img2: "Pics/man/2.jpg",
    img3: "Pics/man/3.jpg",
    img4: "Pics/man/4.jpg",
    img5: "Pics/man/5.jpg",
  },
  {
    id: 63,
    title: "Cross Body Bag",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/man/6.jpg",
    img1: "Pics/man/6.jpg",
    img2: "Pics/man/7.jpg",
    img3: "Pics/man/8.jpg",
    img4: "Pics/man/9.jpg",
    img5: "Pics/man/10.jpg",
  },
  {
    id: 64,
    title: "Mini Shoulder Bag",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/man/20.jpg",
    img1: "Pics/man/20.jpg",
    img2: "Pics/man/21.jpg",
    img3: "Pics/man/22.jpg",
    img4: "Pics/man/23.jpg",
    img5: "Pics/man/21.jpg",
  },
  {
    id: 66,
    title: "Interlock T-shirt",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/boy/a1.jpg",
    img1: "Pics/boy/a1.jpg",
    img2: "Pics/boy/a2.jpg",
    img3: "Pics/boy/a3.jpg",
    img4: "Pics/boy/a4.jpg",
    img5: "Pics/boy/a5.jpg",
  },
  {
    id: 67,
    title: "Regular Denim Shorts",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/boy/s1.jpg",
    img1: "Pics/boy/s1.jpg",
    img2: "Pics/boy/s2.jpg",
    img3: "Pics/boy/s3.jpg",
    img4: "Pics/boy/s4.jpg",
    img5: "Pics/boy/s5.jpg",
  },
  {
    id: 68,
    title: "Black Jacket",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/boy/j1.jpg",
    img1: "Pics/boy/j1.jpg",
    img2: "Pics/boy/j2.jpg",
    img3: "Pics/boy/j3.jpg",
    img4: "Pics/boy/j1.jpg",
    img5: "Pics/boy/j3.jpg",
  },
  {
    id: 69,
    title: "Sneakers",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/boy/k1.jpg",
    img1: "Pics/boy/k1.jpg",
    img2: "Pics/boy/k2.jpg",
    img3: "Pics/boy/k3.jpg",
    img4: "Pics/boy/k4.jpg",
    img5: "Pics/boy/k5.jpg",
  },
  {
    id: 70,
    title: "Sandals",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/girl/e1.jpg",
    img1: "Pics/girl/e1.jpg",
    img2: "Pics/girl/e2.jpg",
    img3: "Pics/girl/e3.jpg",
    img4: "Pics/girl/e4.jpg",
    img5: "Pics/girl/e5.jpg",
  },
  {
    id: 71,
    title: "Lifestyle Sneakers",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/girl/d1.jpg",
    img1: "Pics/girl/d1.jpg",
    img2: "Pics/girl/d2.jpg",
    img3: "Pics/girl/d3.jpg",
    img4: "Pics/girl/d4.jpg",
    img5: "Pics/girl/d5.jpg",
  },
  {
    id: 72,
    title: "Mini Dress",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/girl/a1.jpg",
    img1: "Pics/girl/a1.jpg",
    img2: "Pics/girl/a2.jpg",
    img3: "Pics/girl/a3.jpg",
    img4: "Pics/girl/a4.jpg",
    img5: "Pics/girl/a5.jpg",
  },
  {
    id: 73,
    title: "Regular Shirts",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/girl/c1.jpg",
    img1: "Pics/girl/c1.jpg",
    img2: "Pics/girl/c2.jpg",
    img3: "Pics/girl/c3.jpg",
    img4: "Pics/girl/c4.jpg",
    img5: "Pics/girl/c5.jpg",
  },
  {
    id: 74,
    title: "Slim Straight Fit jean",
    price: "$ " + 8.95,
    size: ["S", "M", "L"],
    show: "Pics/girl/b1.jpg",
    img1: "Pics/girl/b1.jpg",
    img2: "Pics/girl/b2.jpg",
    img3: "Pics/girl/b3.jpg",
    img4: "Pics/girl/b4.jpg",
    img5: "Pics/girl/b5.jpg",
  },
];
const urlParams = new URLSearchParams(window.location.search);
const id = parseInt(urlParams.get("id"));
const product = products.find((p) => p.id === id);

if (product) {
  document.getElementById("title").textContent = product.title;
  document.getElementById("price").textContent = product.price;
  document.getElementById("show").src = product.show;
  document.getElementById("img1").src = product.img1;
  document.getElementById("img2").src = product.img2;
  document.getElementById("img3").src = product.img3;
  document.getElementById("img4").src = product.img4;
  document.getElementById("img5").src = product.img5;
} else {
  document.getElementById("title").textContent = "Asymmetrical Fitted T-shirt";
}
